version: '3.8'

services:
  # n8n automation tool
  n8n:
    image: n8nio/n8n
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=${N8N_USER_DB_PASSWORD}
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=${N8N_ADMIN_PASSWORD}
      - N8N_SMTP_HOST=mailhog
      - N8N_SMTP_PORT=1025
      - N8N_SMTP_USER=n8n
      - N8N_SMTP_PASS=n8n
      - N8N_SMTP_SENDER=contact@n8n.com
      - GENERIC_TIMEZONE=Europe/London
    ports:
      - "5678:5678"
    depends_on:
      - postgres
    restart: always

  # PostgreSQL database
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=password
      - N8N_USER_DB_PASSWORD=${N8N_USER_DB_PASSWORD}
      - ELC_USER_DB_PASSWORD=${ELC_USER_DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    #command: ["bash", "/docker-entrypoint-initdb.d/init.sh"]
    ports:
      - "5432:5432"
    restart: always

  # Mailhog for capturing emails
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: always

  # SFTP server
  sftp:
    image: atmoz/sftp
    hostname: atmoz
    ports:
      - "2222:22"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - sftp-data:/home
    environment:
      SFTP_USERS: ${SFTP_USERS}
    restart: always

  # MinIO for Blob Storage
  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data
    volumes:
      - minio-data:/data
    ports:
      - "9000:9000"  # MinIO API Port
      - "9001:9001"  # MinIO Console Port
    restart: always

  # MinIO Console (for management)
  minio-console:
    image: minio/mc
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      mc alias set minio http://minio:9000 admin ${MINIO_ROOT_PASSWORD};
      mc mb minio/elc;
      mc policy set public minio/elc
      "

  # ELC api
  api:
    build: ./api
    ports:
      - '3000:3000'
    environment:
      DB_HOST: postgres
      DB_USER: elc
      DB_PASSWORD: ${ELC_USER_DB_PASSWORD}
      DB_DATABASE: elc
      DB_PORT: 5432
      MINIO_ENDPOINT: 127.0.0.1
      MINIO_PORT: 9000
      MINIO_ACCESS_KEY: NULL
      MINIO_SECRET_KEY: NULL
    depends_on:
      - postgres
      - minio
    
  # Fake LXP
  app:
    build:
      context: ./app
    ports:
      - '80:80'
    depends_on:
      - api

volumes:
  postgres-data:
  sftp-data:
  minio-data: